# Generated by Django 2.2.1 on 2019-06-28 14:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('isbn', models.TextField()),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('number_of_pages', models.PositiveIntegerField()),
                ('publisher', models.TextField()),
                ('country', models.TextField()),
                ('release_date', models.DateField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'books_details',
            },
        ),
    ]
